version: '3'

services:
  apprise:
   # Un-comment the below to use the latest image from GitHub Container Registry
   # image: ghcr.io/progress-i360/apprise-api:latest
    build:
      context: .
      dockerfile: Dockerfile.optimized
      target: api-only-alpine
    container_name: apprise
    # Environment for using stateless mode
    environment:
      - APPRISE_STATEFUL_MODE=DISABLED
      - APPRISE_ATTACH_SIZE=0
      - APPRISE_STORAGE_MODE=memory
      - APPRISE_CONFIG_LOCK=yes
    ports:
      - 8000:8000
    # Volumes not required for stateless mode
    # Uncomment the below if you want to use bind mounts for configuration or attachments
    # volumes:
    #   - ./apprise_api:/opt/apprise/webapp:ro
      # if uncommenting the below, you will need to type the following
      # Note: if you opt for bind mount config file consider setting env var APPRISE_STATEFUL_MODE to simple with appropriate file format
      # otherwise the django instance won't have permissions to write
      # to the directory correctly:
      #   $> chown -R 33:33 ./config
      #   $> chmod -R 775 ./config
      # - ./config:/config:rw
      # Note: The attachment directory can be exposed outside of the container if required
      #   $> chown -R 33:33 ./attach
      #   $> chmod -R 775 ./attach
      # - ./attach:/attach:rw

  ## Un-comment the below and then access a testing environment with:
  ##    docker-compose run test.py310 build
  ##    docker-compose run --service-ports --rm test.py310 bash
  ##
  ## From here you
  ## > Check for any lint errors
  ##    flake8 apprise_api
  ##
  ## > Run unit tests
  ##    pytest apprise_api
  ##
  ## > Host service (visit http://localhost on host pc to access):
  ##   ./manage.py runserver 0.0.0.0:8000
  # test.py312:
  #   ports:
  #     - 8000:8000
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.py312
  #   volumes:
  #     - ./:/apprise-api
