name: Build Apprise API Images

on:
#   push:
#     branches: ["*"]
#     tags:
#       - v*
#   pull_request:
#     branches: ["master"]

  # Allow job to be triggered manually.
  workflow_dispatch:
    inputs:
      build_variant:
        description: 'Build variant to create'
        required: true
        default: 'runtime'
        type: choice
        options:
        - runtime
        - api-only
        - runtime-distroless
        - api-only-distroless
        - api-only-alpine

jobs:
  buildx:
    name: Build Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - name: "runtime"
            suffix: ""
          - name: "api-only"
            suffix: "-api-only"
          - name: "runtime-distroless"
            suffix: "-distroless"
          - name: "api-only-distroless"
            suffix: "-api-only-distroless"
          - name: "api-only-alpine"
            suffix: "-api-only-alpine"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set the GitHub Container Registry repository name for the current organization
      - name: Set ghcr repository name
        id: set-ghcr-repository
        run: |
          ghcr_name=$(echo "${{ github.repository_owner }}/apprise-api" | awk '{ print tolower($0) }')
          echo "Name is ${ghcr_name}"
          echo "ghcr-repository=${ghcr_name}" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ steps.set-ghcr-repository.outputs.ghcr-repository }}
          tags: |
            type=semver,event=tag,pattern={{version}}${{ matrix.variant.suffix }}
            type=semver,event=tag,pattern={{major}}.{{minor}}${{ matrix.variant.suffix }}
            type=edge,branch=master,suffix=${{ matrix.variant.suffix }}
            type=ref,event=branch,suffix=${{ matrix.variant.suffix }}
            type=sha,prefix={{branch}}-,format=short,suffix=${{ matrix.variant.suffix }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.optimized
          target: ${{ matrix.variant.name }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.variant.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.variant.name }}

      - name: Run Trivy vulnerability scanner
        if: github.event_name != 'pull_request' && steps.build.outcome == 'success'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ fromJSON(steps.docker_meta.outputs.json).tags[0] }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Display Trivy scan results (Table format)
        if: github.event_name != 'pull_request' && steps.build.outcome == 'success' && always()
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ fromJSON(steps.docker_meta.outputs.json).tags[0] }}
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy scan results to GitHub Security tab
        if: github.event_name != 'pull_request' && steps.build.outcome == 'success'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Grype vulnerability scanner
        if: github.event_name != 'pull_request' && steps.build.outcome == 'success'
        uses: anchore/scan-action@v6
        id: grype
        with:
          image: ${{ fromJSON(steps.docker_meta.outputs.json).tags[0] }}
          severity-cutoff: medium

      - name: Display Grype scan results (Table format)
        if: github.event_name != 'pull_request' && steps.build.outcome == 'success' && always()
        uses: anchore/scan-action@v6
        with:
          image: ${{ fromJSON(steps.docker_meta.outputs.json).tags[0] }}
          output-format: table
          fail-build: false
          severity-cutoff: medium

      - name: Upload Grype scan results to GitHub Security tab
        if: github.event_name != 'pull_request' && steps.build.outcome == 'success' && always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.grype.outputs.sarif }}
